### PR TITLE
Implement nautilus sampler interface

### PR DESCRIPTION
**Pull request by johannesulf**
This PR adds the nautilus sampler (https://nautilus-sampler.readthedocs.io/). I could need some help ensuring that everything works as expected.

* blobs: Nautilus supports blobs. The interface is very similar to emcee's. But I still need to figure out how to give those results back to CosmoSIS.
* MPI: Nautilus supports MPI parallelization via schwimmbad or any pool with a `map` method, just like emcee and dynesty. Seeing how dynesty and emcee are interfaced, MPI parallelization may already work. But that needs to be tested.
* tests: No unit tests have been implemented yet.

### CODE REVIEW

**Comment by joezuntz** [comment]
Hi @johannesulf - thanks so much, this is brilliant! I'll look at the interface for derived parameters this week.

**Comment by joezuntz** [comment]
@johannesulf - I've made some changes - thanks for giving me access.

I've added the blob thing, that worked fine thanks!

For the "resume" feature I had to add a few bits of supporting code to the wider cosmosis, which is really useful elsewhere too.  I've also added the postprocessing and a quick test.

**Comment by johannesulf** [comment]
Wonderful! I quickly tested MPI and it seems to work fine. The implementation of blobs looks very good. But I haven't done any extensive tests.

**Comment by joezuntz** [comment]
Thanks so much for this - looking forward to testing it out.

**Pull request merged**
