### PR TITLE
Update nautilus integration to 1.0

### PR DESCRIPTION
**Pull request by johannesulf**
This PR should update the nautilus sampler integration to version 1.0. Currently, `cosmosis` actually only supports nautilus version 0.6. What was the reason for not supporting 0.7? By the way, the updates in 0.7 and 1.0 are fairly minor. Still, it would be good to update cosmosis to nautilus 1.0.

### CODE REVIEW

**Comment by johannesulf** [comment]
Looks like version 1.0.0 actually introduced a bug when handling blobs. That's what's causing the test failure. Cosmosis is handling blobs in a slightly unusual way that's currently not covered in any of my tests. I'll release a new version 1.0.1 soon and make sure that future versions of nautilus have tests for the way cosmosis handles blobs.

**Comment by johannesulf** [comment]
Looks good now. The two test failures are due to me updating the cosmosis branch too quickly after publishing nautilus 1.0.1. In these two cases, pip still installed the older version 1.0.0.

**Comment by joezuntz** [comment]
Sorry for the delay on this - I'm on paternity leave but will be back in June to review.

**Review by joezuntz — APPROVED** [review]

**Comment by joezuntz** [comment]
Thanks for this!

**Pull request merged**
