### PR TITLE
n_steps control for pocoMC

### PR DESCRIPTION
**Pull request by minaskar**
Added support for controlling the number of MCMC steps per iteration

### CODE REVIEW

**Comment by joezuntz** [comment]
Looks like you just have a typo, self->seld.

**Comment by minaskar** [comment]
Thanks Joe! It should be fine now.

**Comment by minaskar** [comment]
The failed test seems to be irrelevant to pocoMC?

**Comment by minaskar** [comment]
Hi @joezuntz, I don't see anything causing issues here. Any ideas why the test failed?

**Comment by joezuntz** [comment]
This is fixed in the main branch, so I can merge.

**Review by joezuntz — APPROVED** [review]

**Pull request merged**
